version: "2.3"

services:
  weka:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - JAVA_TOOL_OPTIONS=${WEKA_JAVA_OPTS}
      - CLASSPATH=${WEKA_CLASSPATH}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${WEKA_DATA_DIR:-~/}:/data
      - ${WEKA_RESULT_DIR:-~/}:/result
      - ${WEKA_JAR_DIR:-~/}:/jars

